yarnPath: .yarn/releases/yarn-3.2.4.cjs
enableGlobalCache: false
nodeLinker: node-modules

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"

npmScopes:
  luxonis:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmPublishRegistry: "https://npm.pkg.github.com"
    npmRegistryServer: "https://npm.pkg.github.com"