name: Build and publish NPM

on:
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  NODE_VERSION: "18.5.0"

jobs:
  build:
    strategy:
      matrix:
        runner: ["buildjet-2vcpu-ubuntu-2204", "buildjet-2vcpu-ubuntu-2204-arm"]
    runs-on: ${{ matrix.runner }}
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@luxonis"
      - name: Build
        run: |
          sudo apt-get update && sudo apt-get install -y libusb-1.0-0-dev
          yarn install
          yarn run prepare-prebuilds
          yarn run clean
        env:
          CI: true
      - uses: actions/upload-artifact@v3
        with:
          name: prebuilds-${{ matrix.runner }}
          path: prebuilds/*.node
  
  publish:
    runs-on: buildjet-2vcpu-ubuntu-2204
    needs: ["build"]
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://npm.pkg.github.com/"
          scope: "@luxonis"
      - uses: actions/download-artifact@v3
        with:
          path: all-prebuilds
      - name: Publish
        run: |
          echo "Prepared prebuilds..."
          npm install
          npm run relocate-prebuilds
          
          echo "Validating..."
          npm install
          npm run test

          echo "Publishing..."
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}